signs:
  updateInterval: 100
  lineModel:
    - '[§2{server_name}§r]'
    - ''
    - '» §5{player_count} §rof §5{max_player_count} §rplayers'
    - '» {status_color_code}{status}'
  states:
    online:
      color: green
      material: green_concrete
    offline:
      color: red
      material: red_concrete
    full:
      color: yellow
      material: yellow_concrete
messages:
  prefix: '§8[§eSigns§8] §a'
  serverOffline: '§cThis server is offline!'
  serverFull: '§cThis server is full!'
  insufficientPermissions: '§cYou do not have the required permission(s) to execute this command!'
  invalidUsage: '§cYou need to specify the name of the server you want to use.'
  noSign: '§cYou have to look at a sign.'
  signAlreadyRegistered: '§cThis sign is already registered as a server sign.'
  signSuccessfullyRegistered: 'You successfully registered this sign.'
  signSuccessfullyRemoved: 'You successfully removed this sign.'